### ISSUE TITLE
Add more resources for more languages.

### ISSUE THREAD

**Issue by IvanovCosmin** [IvanovCosmin/awesome-natural-approach#1]
More natural approach/tprs/comprehension focused free resources should be added

**Comment by ashish-garg18** [comment]
Can you please elaborate your issue?

**Comment by DrDru** [comment]
For Japanese : 

https://www.youtube.com/c/ComprehensibleJapanese/featured A Youtube channel with a lot of videos with comprehensible input

https://drdru.github.io/ a comprehensible input website (it's mine) 

https://tadoku.org/japanese/en/free-books-en/ Free Tadoku graded readers

**Comment by IvanovCosmin** [comment]
Hi @DrDru. Thank for you submissions. I am adding them right now. I really like your website, I've played with it for some minutes and I really respect your work. keep it going :D

**Comment by DrDru** [comment]
Thank you for the kind word :-)
